### ISSUE TITLE
Essensplan - aktueller Tag wird nicht angezeigt

### ISSUE THREAD

**Issue by MaxGer** [LucasG04/foodly_app#25]

**Comment by LucasG04** [comment]
Kannst du das reproduzieren? Ist das evtl. ein bestimmter Tag an dem das Problem auftritt?

**Comment by MaxGer** [comment]
Ne, dass ist immer. Habe gerade nochmal geschaut, die Essensplanung beginnt mit Montag und nicht mit Sonntag. Wenn ich die Planung letzte Woche gemacht hätte, wüsste ich ja gar nicht mehr was für heute geplant ist

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
