### ISSUE TITLE
Einkaufsliste - löschen swippable

### ISSUE THREAD

**Issue by MaxGer** [LucasG04/foodly_app#26]
Um einen Eintrag zu löschen muss man aktuell swipen + tippen.

Wünschenswert wäre eine flüssige "swipe" Bewegung zu machen und der Eintrag wäre gelöscht (ohne zusätzliches tippen).

**Comment by LucasG04** [comment]
Um es als gekauft zu markieren, musst du es antippen. Man kann dann später die gekauften items mit dem Button "Alle entfernen" entfernen. Hast du da noch nen Vorschlag?
![image](https://user-images.githubusercontent.com/42368417/144923788-8cd8da29-c1a2-4e9f-8a22-c9b325d39a78.jpeg)

**Comment by LucasG04** [comment]
Swipe/Löschen wurde entfernt. Es gibt nur noch den Flow: tippen -> "Alle löschen" in bereits gekauft.
