### ISSUE TITLE
Essensplan - keine Vorschläge bei neuem Gericht

### ISSUE THREAD

**Issue by MaxGer** [LucasG04/foodly_app#27]
Wenn man ein neues Gericht hinzufügen möchte bekommt man keine Liste der Gerichte sondern muss sich an den eingespeicherten Namen erinnern

**Comment by LucasG04** [comment]
Durch (endlich) #49 werden max. 10 Gerichte als Vorschläge angezeigt, die auch als Gerichte hinterlegt sind (5x am längsten nicht geplant + 5x am wenigsten geplant (ergibt das Sinn?)). Passt damit das issue oder hast du noch einen Vorschlag?
