### ISSUE TITLE
Gruppierung der Einkaufsliste

### ISSUE THREAD

**Issue by MaxGer** [LucasG04/foodly_app#28]
Gruppierung in die verschiedene Bereiche beim einkaufen, alle Läden sind ja in etwa gleich aufgebaut

1. Obst/Gemüse
-- tdb ---
2. Trockenzeug (Nudeln/Reis)
3. Backzeug
4. Kühl-, Tiefkühlabteilung
5. Getränke

gruppierung vielleicht auch selbst anpassbar?

**Comment by LucasG04** [comment]
Erste Schritte sind mit #155 schon gemacht: Vorschläge die von der API kommen, beinhalten eine ID für eine "Grocery Group". Diese kann mit einer Liste von allen Gruppen verknüpft werden.

**Comment by LucasG04** [comment]
API von REWE kann noch verwendet werden, um mehr Produkte zu bieten:

```
https://shop.rewe.de/api/products
```
