### ISSUE TITLE
Dragable Items in Week-Preview

### ISSUE THREAD

**Issue by MaxGer** [LucasG04/foodly_app#59]
Hi, stelle mal ganz dreist einen request hier rein :)

Es passiert mir häufiger, dass die Wochenplanung nicht perfekt ist, bzw. irgendetwas dazwischen kommt (man geht essen / hat kein Bock und macht eine Pizza).

Dann ist es ziemlich pain, jeden Eintrag zu löschen und neu einzutragen, da man das ja dann für alle Gerichte in der Woche machen muss.

Die einfach per drag&drop verschieben zu können, wäre schon ziemlich strong.

**Comment by LucasG04** [comment]
Kann ich verstehen und geht mir auch manchmal so. Drag&drop hört sich erstmal tricky an. Aktuell bin ich an #58 dran.

**Comment by LucasG04** [comment]
Wird geschlossen & bei Bedarf wieder geöffnet.
