### ISSUE TITLE
Einkaufsliste: Bereits Gekauft irgendwie immer vollgespamt

### ISSUE THREAD

**Issue by MaxGer** [LucasG04/foodly_app#96]
Die Liste mit bereits gekauft ist immer voll und der Button zum löschen ganz unten

Der Use-Case wäre doch, falls man aus Versehen ein Item gelöscht hat?

Könnte man dafür nicht auch eine Snackbar nehmen die für 3s kurz aufpoppt und beim anklicken das Rückgängig macht?

Dann hätte man das mit dem Spam gelöst 🤔

**Comment by LucasG04** [comment]
Finde ich gut. Werde es aber in eine Einstellung packen.
